#!/usr/bin/env python3
"""Convert cloze_all.json into js/data/cloze.js.

cloze_all.json is the source of truth: hand-written fill-in-the-blank cards,
five per word, one of each anchor type. The app cannot read JSON without a
fetch, so this writes the same cards out as an ES module - data only, no
logic. Re-run it after every edit to the JSON; a second run with no edit
changes nothing.

    python3 tools_cloze.py [path/to/cloze_all.json]

A card that breaks the schema stops the run with a message naming it, and
nothing is written.
"""
import json, pathlib, re, sys

root = pathlib.Path(__file__).parent
src = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else root / 'cloze_all.json'
out = root / 'js' / 'data' / 'cloze.js'

ANCHOR = {'consequence': 'cq', 'cause': 'ca', 'contrast': 'ct',
          'definition_in_context': 'df', 'collocation': 'cl'}
BLANK = '____'
CARDS_PER_WORD = 5

# the headwords the app knows, read straight from words.js so an id that
# points at the wrong word is caught here and not in front of a learner
headwords = {int(i): w for i, w in
             re.findall(r'\{"id": (\d+), "word": "([^"]+)"', (root / 'js' / 'data' / 'words.js').read_text())}

errors = []
def check(ok, where, msg):
    if not ok: errors.append(f'{where}: {msg}')
    return ok

def card_of(word_id, n, c):
    where = f'word {word_id} card {n}'
    s, a = c.get('sentence', ''), c.get('answer', '').strip()
    check(s.count(BLANK) == 1 and '_' * 5 not in s, where, f'needs exactly one {BLANK}: {s!r}')
    tokens = s.split()
    check(8 <= len(tokens) <= 16, where, f'{len(tokens)} words, want 8-16: {s!r}')
    at = next((k for k, t in enumerate(tokens) if BLANK in t), None)
    check(at is None or at >= 2, where, f'the blank is in the first two words: {s!r}')
    check(a != '', where, 'empty answer')
    check(c.get('anchor') in ANCHOR, where, f'unknown anchor {c.get("anchor")!r}')
    alt = [x.strip().lower() for x in c.get('also_accept', [])]
    check(a.lower() not in alt, where, f'also_accept contains the answer {a!r}')
    unique = c.get('checks', {}).get('unique')
    check(unique == (not alt), where, 'checks.unique must be false exactly when also_accept is set')
    why = {}
    for r in c.get('rejected', []):
        if check(' — ' in r, where, f'rejected entry has no " — ": {r!r}'):
            key, reason = r.split(' — ', 1)
            why[key.strip().lower()] = reason.strip()
    check(len(why) >= 1, where, 'no rejected words')
    return {'id': f'{word_id}:{n}', 's': s, 'a': a, 't': ANCHOR.get(c.get('anchor')),
            'alt': alt, 'why': why}

data = json.loads(src.read_text(encoding='utf-8'))
cloze = {}
for w in sorted(data, key=lambda w: w['id']):
    wid = w['id']
    check(headwords.get(wid) == w.get('word'), f'word {wid}',
          f'{w.get("word")!r} is {headwords.get(wid)!r} in words.js')
    check(wid not in cloze, f'word {wid}', 'appears twice')
    cards = [card_of(wid, n, c) for n, c in enumerate(w.get('cards', []))]
    check(len(cards) == CARDS_PER_WORD, f'word {wid}', f'{len(cards)} cards, want {CARDS_PER_WORD}')
    check(len({c['t'] for c in cards}) == len(cards), f'word {wid}', 'two cards share an anchor')
    cloze[wid] = cards

if errors:
    sys.exit('cloze_all.json breaks the schema, nothing written:\n  ' + '\n  '.join(errors))

lines = ['// Cloze cards: five hand-written gap fills per word, one per anchor type.',
         '// Generated by tools_cloze.py from cloze_all.json - edit the JSON, not this.',
         '//   s sentence with ____   a answer as it fills the blank',
         '//   t anchor: df definition, cq consequence, ca cause, ct contrast, cl collocation',
         '//   alt other words that also fit   why rejected word -> why it does not',
         'export const cloze = {']
for wid, cards in cloze.items():
    lines.append(f'  {wid}: [')
    lines += [f'    {json.dumps(c, ensure_ascii=False)},' for c in cards]
    lines.append('  ],')
lines.append('};')
out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'wrote {out.relative_to(root)}: {len(cloze)} words, {sum(map(len, cloze.values()))} cards')
